### ISSUE TITLE
Excuse me, can you explain the project?

### ISSUE THREAD

**Issue by qifnegle** [janelchua/Phase-field-and-Peridynamics#1]

**Comment by qifnegle** [comment]
Excuse me, can you explain the project?

**Comment by qifnegle** [comment]
Excuse me, can you explain the project?

**Comment by janelchua** [comment]
Hi, this project is about doing initial-boundary simulations as well as travelling wave calculations using strain gradient model, peridynamics and phase-field model (some of the most popular models used to simulate interfaces in motion). 
The results are written up in the following paper: https://doi.org/10.1016/j.jmps.2021.104716
